apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: registro-prod
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        cluster: 'registro-prod'
    
    scrape_configs:
      - job_name: 'api-service'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - registro-prod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: registro-api
          - source_labels: [__meta_kubernetes_pod_ip]
            target_label: __address__
            replacement: $1:8080
